### ISSUE TITLE
unflatten

### ISSUE THREAD

**Issue by Edaurd** [sirjonasxx/G-BuildTools#11]
![image](https://user-images.githubusercontent.com/23409271/126018439-9eb4ee58-02fb-4b1f-a7bd-09de801cc958.png)
![image](https://user-images.githubusercontent.com/23409271/126018625-b0c301ac-39b8-45b3-b889-a46456e5af05.png)
![image](https://user-images.githubusercontent.com/23409271/126018567-8e83e9ef-a9fb-4ebd-a6fd-f12c03dec5aa.png)

**Comment by sirjonasxx** [comment]
how should the order be decided?

**Comment by sirjonasxx** [comment]
better use :undo for now
