### ISSUE TITLE
"Furni Mover" doesn't move all furniture

### ISSUE THREAD

**Issue by HabboMaik** [sirjonasxx/G-BuildTools#6]
The **furni mover** and **stacktiles at the same height** option doesn't work as they should. 
GIFS: https://imgur.com/a/GRonfVz

**Comment by HabboMaik** [comment]
Slow mode is also the same like fast mode in settings

**Comment by sirjonasxx** [comment]
Does the issue still occur if you use G-BuildTools 1.1 and move the ratelimit slider all the way to the left?

If yes, does it still occur if you enable "Packet spam" and set it to a higher number than 2?

If these steps didn't help (no improvement) then let me know when you're online and ill come visit

**Comment by HabboMaik** [comment]
Issue solved! Thank you!
Just move the ratelimit slider to the **right**.
